-- The things only the owner can do before brand deals go live (state of 9 Oct 2026), as manual tasks on the admin "Offen" page.
-- Data only: idempotent through the dedupe key, and the owner can tick them off or delete them there like any manual task.
INSERT INTO "AdminTask" ("id", "title", "reason", "priority", "source", "status", "href", "dedupeKey", "updatedAt")
VALUES
  (gen_random_uuid()::text, 'Stripe Live: 3 Webhook-Events ergänzen', 'charge.refunded, charge.dispute.created, charge.dispute.closed beim Live-Endpoint (Developers, Webhooks). Ungefährlich: unbekannte Charges werden ignoriert.', 'HIGH', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:stripe-live-events', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Anwalt: AGB, Datenschutz und Geldfluss für Deals', 'AGB für Deals, Datenschutz (Beleg-Bilder 90 Tage, Rechnungs-Mails), Einordnung des Geldflusses (ZAG), Vertragstext in contract.ts, Wortwahl „sicher hinterlegt“. Fragenliste: docs/brand-deals.md, Abschnitt „Needs a lawyer or a tax adviser“.', 'HIGH', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:lawyer', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Steuerberater: Rechnungen und Umsatzsteuer für Deals', 'Gutschriftsverfahren § 14 Abs. 2 UStG, Umsatzsteuer, Storno + Neuausstellung, E-Rechnung ab 1.1.2027, Zusammenfassende Meldung, DAC7. Dazu: Modell verschlanken (Vermittlungsprovision statt Rechnungen im Namen der Creator)?', 'HIGH', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:tax-adviser', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Vor dem Einschalten: Steuerdaten von comtor in Vercel', 'IMPRINT_VAT_ID oder PLATFORM_TAX_NUMBER und PLATFORM_SMALL_BUSINESS (Production). Ohne sie werden keine Rechnungen ausgestellt. BRAND_DEALS_ENABLED bleibt in Production aus, bis Anwalt und Steuerberater durch sind.', 'HIGH', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:platform-tax-data', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Preview: AUTH_SECRET setzen und neu deployen', 'Ohne AUTH_SECRET im Scope Preview kommt beim Login „problem with the server configuration“. Wert: openssl rand -base64 33, danach Redeploy ohne Build-Cache.', 'MEDIUM', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:preview-auth-secret', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Preview: Variablen prüfen', 'Scope Preview: BRAND_DEALS_ENABLED=1 (sonst fehlt „Deals“), DATABASE_URL_PREVIEW, Stripe-Testkeys, RESEND_API_KEY, EMAIL_FROM, CRON_SECRET, IMPRINT_VAT_ID (Platzhalter). Production-Variablen nicht anfassen. Offen: Fehler P1001 beim ersten Migrationslauf.', 'MEDIUM', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:preview-env', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Stripe-Webhook und Testdurchlauf mit Testkarten', 'Lokal mit der Stripe CLI (stripe listen --forward-to …/api/webhooks/stripe). Durchlauf: Zahlung 4242…, Entwurf, Post, Cron von Hand, Auszahlung, Rechnung + Mail, Rückerstattung, Chargeback mit 4000 0000 0000 0259.', 'MEDIUM', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:stripe-test-run', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Resend: Testmail aus der Preview senden', 'Unter /admin/email. Ohne verifizierte Absenderdomain gehen Hinweis-Mails und Rechnungs-PDFs nicht raus.', 'MEDIUM', 'MANUAL', 'OPEN', '/admin/email', 'manual:2026-10-09:resend-test', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Meta-App-Prüfung für Instagram-oEmbed anstoßen', 'Meta for Developers: App mit „oEmbed Read“, App Review (Tage bis Wochen). Danach META_OEMBED_TOKEN (<App-ID>|<Secret>). Bis dahin: Instagram-Posts per Screenshot, den die Marke bestätigt.', 'MEDIUM', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:meta-review', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Texte der Deals gegenlesen', '24 Hinweise und Mails (Deutsch, Englisch) in notices.ts und email-templates.ts, dazu die neuen Texte für Checkliste, Filter, Vorlagen und Builder in ui-copy*.ts.', 'MEDIUM', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:proofread-texts', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Neue Oberfläche auf echtem iPhone und in Safari ansehen', 'Getestet ist nur Chromium (390 px). Offen: feste Speichern-Leiste im Briefing, ⋯-Menü, Safe-Area, Tastatur.', 'MEDIUM', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:safari-ios', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Nach dem Deploy prüfen', 'Migrationen angewendet, Cron deal-deadlines läuft täglich 08:00 UTC, Stripe-Webhook-Zustellungen ohne Fehler, /admin/deals und diese Seite.', 'MEDIUM', 'MANUAL', 'OPEN', '/admin/technik', 'manual:2026-10-09:post-deploy', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Optional: YOUTUBE_API_KEY und SOCIAL_WEBHOOK_SECRET', 'YOUTUBE_API_KEY (Google Cloud, YouTube Data API v3): Views und Likes bei YouTube-Posts. SOCIAL_WEBHOOK_SECRET nur, wenn ein Dienst Metriken an /api/webhooks/social schickt.', 'LOW', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:optional-keys', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Entscheidungen: Vercel Pro, Speicher, Beispielvorlagen, Entdecken', 'Vercel Pro für stündlichen Cron; Speicher-Anbieter für Datei-Upload der Entwürfe; Beispielvorlagen für Briefings mitliefern; „Entdecken“ in den Feed holen. Details: docs/ux-backlog.md.', 'LOW', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:decisions', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'Admin-Bereich auf Handy, Dunkelmodus und Tablet prüfen', 'Bisher nur Desktop und 390 px per Screenshot geprüft.', 'LOW', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:admin-devices', CURRENT_TIMESTAMP),
  (gen_random_uuid()::text, 'npm audit: 4 hohe Meldungen (sharp / librsvg)', 'CI prüft nur „kritisch“ und ist grün; die Meldungen waren vorher da. Beim nächsten Dependabot-Lauf mitnehmen.', 'LOW', 'MANUAL', 'OPEN', NULL, 'manual:2026-10-09:npm-audit', CURRENT_TIMESTAMP)
ON CONFLICT ("dedupeKey") DO NOTHING;
