type Text = { de: string; en: string };

export const BUSINESS_WORDS = {
  "business.title": { en: "Business details", de: "Geschäftsdaten" },
  "business.description": {
    en: "Deals are business to business. We need to know who is behind each account, how you are taxed, and we need these details on invoices.",
    de: "Deals laufen zwischen Unternehmen. Wir müssen wissen, wer hinter einem Konto steht und wie du besteuert wirst, und brauchen die Angaben auf Rechnungen.",
  },
  "business.why": {
    en: "Why we ask: EU rules for online marketplaces (Digital Services Act, Art. 30; Platform-to-Business Regulation) require us to know the traders on the platform, and tax law requires complete details on invoices and credit notes. They are not shown to other users, only on documents of your deals.",
    de: "Warum wir fragen: EU-Regeln für Online-Marktplätze (Digital Services Act, Art. 30; P2B-Verordnung) verlangen, dass wir die Händler auf der Plattform kennen, und das Steuerrecht verlangt vollständige Angaben auf Rechnungen und Gutschriften. Sie werden anderen Nutzern nicht angezeigt, nur auf den Belegen deiner Deals.",
  },
  "business.ready": { en: "Your business details are complete.", de: "Deine Geschäftsdaten sind vollständig." },
  "business.missing": { en: "Still missing:", de: "Es fehlt noch:" },
  "business.legalName": { en: "Legal name", de: "Rechtlicher Name" },
  "business.legalNameHint": { en: "Company name, or your full name as a sole proprietor / freelancer.", de: "Firmenname oder dein vollständiger Name als Einzelunternehmer / Freiberufler." },
  "business.type": { en: "Type of business", de: "Art des Unternehmens" },
  "business.type.COMPANY": { en: "Company (GmbH, AG, UG, …)", de: "Unternehmen (GmbH, AG, UG, …)" },
  "business.type.SOLE_PROPRIETOR": { en: "Sole proprietor / trade", de: "Einzelunternehmen / Gewerbe" },
  "business.type.FREELANCER": { en: "Freelancer", de: "Freiberufler" },
  "business.country": { en: "Country", de: "Land" },
  "business.address1": { en: "Street and number", de: "Straße und Hausnummer" },
  "business.address2": { en: "Address line 2 (optional)", de: "Adresszusatz (optional)" },
  "business.postalCode": { en: "Postal code", de: "PLZ" },
  "business.city": { en: "City", de: "Ort" },
  "business.phone": { en: "Phone (optional)", de: "Telefon (optional)" },
  "business.register": { en: "Commercial register no. (optional)", de: "Handelsregisternummer (optional)" },
  "business.taxNumber": { en: "Tax number", de: "Steuernummer" },
  "business.taxNumberHint": { en: "Required in Germany if you have no VAT ID. It has to appear on your credit note.", de: "In Deutschland erforderlich, wenn du keine USt-IdNr. hast. Sie muss auf deiner Gutschrift stehen." },
  "business.vatId": { en: "VAT ID (USt-IdNr.)", de: "USt-IdNr." },
  "business.vatIdHint": {
    en: "Required for businesses in other EU countries: it is checked with the EU's VIES service, and it is what lets us invoice without VAT (reverse charge).",
    de: "Für Unternehmen in anderen EU-Ländern erforderlich: Sie wird mit dem VIES-Dienst der EU geprüft und ermöglicht Rechnungen ohne Umsatzsteuer (Reverse Charge).",
  },
  "business.vatStatus.UNCHECKED": { en: "Not checked yet", de: "Noch nicht geprüft" },
  "business.vatStatus.VALID": { en: "Confirmed by VIES", de: "Von VIES bestätigt" },
  "business.vatStatus.INVALID": { en: "Rejected by VIES", de: "Von VIES abgelehnt" },
  "business.vatStatus.UNAVAILABLE": { en: "VIES not reachable, try again later", de: "VIES nicht erreichbar, versuche es später erneut" },
  "business.vatCheck": { en: "Check again", de: "Erneut prüfen" },
  "business.vatChecked": { en: "VAT ID confirmed.", de: "USt-IdNr. bestätigt." },
  "business.vatRegistered": { en: "Registered as: {name}", de: "Eingetragen als: {name}" },
  "business.vatConsultation": { en: "Consultation no. {number}", de: "Abfragenummer {number}" },
  "business.smallBusiness": { en: "I am a small business and charge no VAT (§ 19 UStG or the small-business scheme of my country).", de: "Ich bin Kleinunternehmer und weise keine Umsatzsteuer aus (§ 19 UStG oder Kleinunternehmerregelung meines Landes)." },
  "business.trader": {
    en: "I act exclusively in the course of my trade, business, craft or profession, not as a consumer, and the details above are correct.",
    de: "Ich handle ausschließlich im Rahmen meiner gewerblichen oder beruflichen Tätigkeit, nicht als Verbraucher, und die Angaben oben sind richtig.",
  },
  "business.selfBilling": {
    en: "I agree that comtor issues credit notes for my services in my name and on my behalf (self-billing, § 14 Abs. 2 UStG). I will tell comtor if my tax details change, and I object to a credit note if it is wrong.",
    de: "Ich stimme zu, dass comtor für meine Leistungen Gutschriften in meinem Namen und für meine Rechnung ausstellt (Gutschriftsverfahren, § 14 Abs. 2 UStG). Ich teile Änderungen meiner Steuerdaten mit und widerspreche einer falschen Gutschrift.",
  },
  "business.save": { en: "Save business details", de: "Geschäftsdaten speichern" },
  "business.saved": { en: "Business details saved.", de: "Geschäftsdaten gespeichert." },
  "business.back": { en: "Back to deals", de: "Zurück zu den Deals" },
  "business.payout": { en: "Payouts are set up in Payments.", de: "Die Auszahlung richtest du unter Zahlungen ein." },
} as const satisfies Record<string, Text>;
