type Text = { de: string; en: string };

export const BRIEFING_WORDS = {
  "briefing.title": { en: "Campaign briefing", de: "Kampagnen-Briefing" },
  "briefing.description": {
    en: "The rules of this campaign. Creators see them before they answer, and a copy becomes the contract when an offer is accepted.",
    de: "Die Regeln dieser Kampagne. Creator sehen sie, bevor sie antworten, und eine Kopie wird zum Vertrag, sobald ein Angebot angenommen wird.",
  },
  "briefing.open": { en: "Campaign briefing", de: "Kampagnen-Briefing" },
  "briefing.openHint": { en: "Formats, advertising label, process, exclusivity and usage rights.", de: "Formate, Werbekennzeichnung, Ablauf, Exklusivität und Nutzungsrechte." },
  "briefing.notSet": { en: "Not written yet: the German defaults apply.", de: "Noch nicht geschrieben: Es gelten die deutschen Standardwerte." },
  "briefing.set": { en: "Written", de: "Geschrieben" },
  "briefing.defaults": { en: "Defaults", de: "Standardwerte" },
  "briefing.back": { en: "Back to the request", de: "Zurück zur Anfrage" },

  "briefing.section.content": { en: "Content", de: "Inhalt" },
  "briefing.section.disclosure": { en: "Advertising label", de: "Werbekennzeichnung" },
  "briefing.section.workflow": { en: "Process and deadlines", de: "Ablauf und Fristen" },
  "briefing.section.exclusivity": { en: "Exclusivity", de: "Exklusivität" },
  "briefing.section.usage": { en: "Usage rights", de: "Nutzungsrechte" },
  "briefing.section.notes": { en: "Notes for the creator", de: "Hinweise für den Creator" },

  "briefing.market": { en: "Market the ad is shown in", de: "Markt, in dem die Werbung läuft" },
  "briefing.marketHint": { en: "Decides which wording counts as a clear advertising label.", de: "Bestimmt, welche Formulierung als klare Werbekennzeichnung gilt." },
  "briefing.market.DE": { en: "Germany", de: "Deutschland" },
  "briefing.market.AT": { en: "Austria", de: "Österreich" },
  "briefing.market.CH": { en: "Switzerland", de: "Schweiz" },
  "briefing.market.FR": { en: "France", de: "Frankreich" },
  "briefing.market.ES": { en: "Spain", de: "Spanien" },
  "briefing.market.IT": { en: "Italy", de: "Italien" },
  "briefing.market.NL": { en: "Netherlands", de: "Niederlande" },
  "briefing.market.PT": { en: "Portugal", de: "Portugal" },
  "briefing.market.PL": { en: "Poland", de: "Polen" },
  "briefing.market.OTHER": { en: "Other (English)", de: "Sonstige (Englisch)" },
  "briefing.formats": { en: "Content to deliver", de: "Zu liefernder Content" },
  "briefing.formatsHint": { en: "Each booked format has to be delivered and verified before the payout.", de: "Jedes gebuchte Format muss geliefert und verifiziert sein, bevor ausgezahlt wird." },
  "briefing.hashtags": { en: "Required hashtags", de: "Pflicht-Hashtags" },
  "briefing.hashtagsHint": { en: "Separated by spaces, without #.", de: "Durch Leerzeichen getrennt, ohne #." },
  "briefing.mentions": { en: "Required mentions", de: "Pflicht-Erwähnungen" },
  "briefing.mentionsHint": { en: "Account names, without @.", de: "Account-Namen, ohne @." },

  "briefing.labels": { en: "Advertising label the creator must use", de: "Werbekennzeichnung, die der Creator nutzen muss" },
  "briefing.labelsHint": {
    en: "It has to stand where it is seen first, in the caption and in the content itself. “#ad” alone is not accepted in most markets. Instructions to leave out the label are not allowed.",
    de: "Sie muss dort stehen, wo man sie zuerst sieht, in der Caption und im Inhalt selbst. „#ad“ allein reicht in den meisten Märkten nicht. Anweisungen, die Kennzeichnung wegzulassen, sind nicht erlaubt.",
  },
  "briefing.partnership": { en: "Also require the platform's paid-partnership label", de: "Zusätzlich das Partnerschafts-Label der Plattform verlangen" },
  "briefing.partnershipHint": { en: "Instagram “Paid partnership”, TikTok content disclosure, YouTube “Includes paid promotion”.", de: "Instagram „Bezahlte Partnerschaft“, TikTok-Inhaltsoffenlegung, YouTube „Enthält bezahlte Werbung“." },

  "briefing.draftRequired": { en: "The creator submits a draft first", de: "Der Creator reicht zuerst einen Entwurf ein" },
  "briefing.draftLead": { en: "Draft due this many days before the posting deadline", de: "Entwurf so viele Tage vor der Posting-Frist fällig" },
  "briefing.reviewDays": { en: "Your review time (days)", de: "Deine Prüfzeit (Tage)" },
  "briefing.reviewDaysHint": { en: "If you don't answer in time, the draft counts as approved.", de: "Antwortest du nicht rechtzeitig, gilt der Entwurf als freigegeben." },
  "briefing.revisions": { en: "Revision rounds", de: "Korrekturrunden" },
  "briefing.windowStart": { en: "Posting window starts", de: "Posting-Fenster beginnt" },
  "briefing.windowEnd": { en: "Post live by", de: "Post online bis" },
  "briefing.windowHint": { en: "Without an end date the creator has 30 days after your payment.", de: "Ohne Enddatum hat der Creator 30 Tage nach deiner Zahlung." },
  "briefing.minLive": { en: "The post has to stay live for", de: "Der Post muss online bleiben für" },
  "briefing.minLiveHint": { en: "The payout waits until this period has passed. If the post disappears, the creator gets 48 hours to publish it again.", de: "Die Auszahlung wartet, bis diese Zeit vorbei ist. Verschwindet der Post, hat der Creator 48 Stunden für eine neue Veröffentlichung." },
  "briefing.live.24": { en: "24 hours", de: "24 Stunden" },
  "briefing.live.72": { en: "3 days", de: "3 Tage" },
  "briefing.live.168": { en: "7 days", de: "7 Tage" },
  "briefing.live.336": { en: "14 days", de: "14 Tage" },
  "briefing.live.720": { en: "30 days", de: "30 Tage" },

  "briefing.exclusivity": { en: "No competing brands around the post", de: "Keine Konkurrenzmarken rund um den Post" },
  "briefing.exclusivityHint": { en: "Exclusivity limits the creator and should be reflected in the price.", de: "Exklusivität schränkt den Creator ein und sollte sich im Preis widerspiegeln." },
  "briefing.categories": { en: "Competing product categories", de: "Konkurrierende Produktkategorien" },
  "briefing.categoriesHint": { en: "Empty: the category of this request.", de: "Leer: die Kategorie dieser Anfrage." },
  "briefing.competitors": { en: "Competing brands by name", de: "Konkurrierende Marken beim Namen" },
  "briefing.competitorsHint": { en: "One per line.", de: "Eine pro Zeile." },
  "briefing.daysBefore": { en: "Days before the post", de: "Tage vor dem Post" },
  "briefing.daysAfter": { en: "Days after the post", de: "Tage nach dem Post" },

  "briefing.usageType": { en: "What may you do with the post?", de: "Was darfst du mit dem Post tun?" },
  "briefing.usageType.ORGANIC_ONLY": { en: "Nothing: it stays on the creator's channel", de: "Nichts: Er bleibt auf dem Kanal des Creators" },
  "briefing.usageType.CROSS_POST": { en: "Repost on our own channels (no ads)", de: "Auf unseren eigenen Kanälen reposten (keine Ads)" },
  "briefing.usageType.PAID_ADS": { en: "Run it as an ad (Partnership Ads, Spark Ads, whitelisting)", de: "Als Anzeige schalten (Partnership Ads, Spark Ads, Whitelisting)" },
  "briefing.channels": { en: "Channels", de: "Kanäle" },
  "briefing.channel.BRAND_ORGANIC_REPOST": { en: "Repost on the brand's own channels", de: "Repost auf den eigenen Kanälen der Marke" },
  "briefing.channel.BRAND_WEBSITE": { en: "Brand website / shop", de: "Website / Shop der Marke" },
  "briefing.channel.META_PARTNERSHIP_ADS": { en: "Meta Partnership Ads (Instagram / Facebook)", de: "Meta Partnership Ads (Instagram / Facebook)" },
  "briefing.channel.TIKTOK_SPARK_ADS": { en: "TikTok Spark Ads", de: "TikTok Spark Ads" },
  "briefing.channel.YOUTUBE_PARTNERSHIP_ADS": { en: "YouTube Partnership Ads", de: "YouTube Partnership Ads" },
  "briefing.channel.WHITELISTING": { en: "Whitelisting (ads through the creator's handle)", de: "Whitelisting (Ads über das Profil des Creators)" },
  "briefing.usageDuration": { en: "For how many days?", de: "Für wie viele Tage?" },
  "briefing.usageFee": { en: "Part of the price that pays for it (€)", de: "Anteil des Preises dafür (€)" },
  "briefing.usageFeeHint": { en: "It is inside your offer amount and shown as its own line on the invoice.", de: "Er steckt im Angebotsbetrag und steht als eigene Zeile auf der Rechnung." },
  "briefing.territory": { en: "Where", de: "Wo" },

  "briefing.talkingPoints": { en: "Talking points", de: "Kernbotschaften" },
  "briefing.doNots": { en: "Please avoid", de: "Bitte vermeiden" },

  "briefing.problems": { en: "To fix before saving", de: "Vor dem Speichern zu beheben" },
  "briefing.warnings": { en: "Worth a look", de: "Einen Blick wert" },
  "briefing.fine": { en: "Everything required is in place.", de: "Alles Nötige ist vorhanden." },
  "briefing.save": { en: "Save briefing", de: "Briefing speichern" },
  "briefing.saved": { en: "Briefing saved.", de: "Briefing gespeichert." },
  "briefing.frozen": { en: "Deals that already exist keep the terms they were made with.", de: "Bestehende Deals behalten die Bedingungen, unter denen sie entstanden sind." },
} as const satisfies Record<string, Text>;
