import type { DealLocale } from "@/lib/deals/copy";
import { fill } from "@/lib/deals/copy";
import { BUSINESS_WORDS } from "@/lib/deals/ui-copy-business";
import { BRIEFING_WORDS } from "@/lib/deals/ui-copy-briefing";

// The words on the deal screens, German and English. Typed by key so a screen can't ask for a text that doesn't exist.

type Text = { de: string; en: string };

const CORE_WORDS = {
  // ----- forms
  "form.working": { en: "Working…", de: "Einen Moment…" },
  "form.somethingWrong": { en: "Something went wrong. Refresh the page and try again.", de: "Etwas ist schiefgegangen. Lade die Seite neu und versuche es erneut." },
  "form.fixBusiness": { en: "Complete your business details →", de: "Geschäftsdaten vervollständigen →" },

  // ----- deals list
  "deals.title": { en: "Deals", de: "Deals" },
  "deals.description": { en: "Every sponsored collaboration from the contract to the payout.", de: "Jede bezahlte Kooperation vom Vertrag bis zur Auszahlung." },
  "deals.yourTurn": { en: "Your turn", de: "Du bist dran" },
  "deals.running": { en: "In progress", de: "Laufend" },
  "deals.finished": { en: "Finished", de: "Abgeschlossen" },
  "deals.empty": { en: "No deals yet", de: "Noch keine Deals" },
  "deals.emptyBrand": { en: "A deal starts when a creator accepts your offer (or you accept theirs).", de: "Ein Deal entsteht, sobald ein Creator dein Angebot annimmt (oder du seins)." },
  "deals.emptyCreator": { en: "A deal starts when a brand accepts your offer (or you accept theirs).", de: "Ein Deal entsteht, sobald eine Marke dein Angebot annimmt (oder du ihres)." },
  "deals.businessBanner": { en: "Your business details are missing. You need them before you can confirm a deal.", de: "Deine Geschäftsdaten fehlen. Du brauchst sie, bevor du einen Deal bestätigen kannst." },
  "deals.businessAction": { en: "Add business details", de: "Geschäftsdaten ergänzen" },
  "deals.heldInDeal": { en: "In escrow. The work, the checks and the payout run on the deal page.", de: "Im Treuhandkonto. Arbeit, Prüfungen und Auszahlung laufen auf der Deal-Seite." },
  "chat.acceptedDeal": { en: "Offer accepted. Open the deal to read and confirm the contract.", de: "Angebot angenommen. Öffne den Deal, um den Vertrag zu lesen und zu bestätigen." },
  "chat.heldDeal": { en: "In escrow. The work, the checks and the payout run on the deal page.", de: "Im Treuhandkonto. Arbeit, Prüfungen und Auszahlung laufen auf der Deal-Seite." },
  "deals.open": { en: "Open deal", de: "Deal öffnen" },
  "deals.invoices": { en: "Invoices", de: "Rechnungen" },
  "deals.businessLink": { en: "Business details", de: "Geschäftsdaten" },

  // ----- status
  "status.CONTRACT_PENDING": { en: "Contract", de: "Vertrag" },
  "status.AWAITING_ESCROW": { en: "Awaiting payment", de: "Zahlung offen" },
  "status.IN_PRODUCTION": { en: "In production", de: "In Arbeit" },
  "status.DRAFT_SUBMITTED": { en: "Draft in review", de: "Entwurf in Prüfung" },
  "status.CHANGES_REQUESTED": { en: "Changes requested", de: "Änderungen gewünscht" },
  "status.DRAFT_APPROVED": { en: "Draft approved", de: "Entwurf freigegeben" },
  "status.POST_SCHEDULED": { en: "Post scheduled", de: "Post geplant" },
  "status.POST_SUBMITTED": { en: "Post being checked", de: "Post wird geprüft" },
  "status.VERIFYING": { en: "Live, hold running", de: "Online, Haltefrist läuft" },
  "status.REPOST_REQUIRED": { en: "Post removed", de: "Post entfernt" },
  "status.PAYOUT_PENDING": { en: "Payout due", de: "Auszahlung fällig" },
  "status.COMPLETED": { en: "Completed", de: "Abgeschlossen" },
  "status.DISPUTED": { en: "Frozen, in review", de: "Eingefroren, in Prüfung" },
  "status.CANCELLED": { en: "Cancelled", de: "Abgebrochen" },

  // ----- lifecycle stages
  "stage.BRIEFING": { en: "Briefing", de: "Briefing" },
  "stage.APPLICATION": { en: "Application", de: "Bewerbung" },
  "stage.AGREEMENT": { en: "Agreement", de: "Vereinbarung" },
  "stage.DRAFT": { en: "Draft", de: "Entwurf" },
  "stage.APPROVAL": { en: "Approval", de: "Freigabe" },
  "stage.SCHEDULING": { en: "Scheduling", de: "Planung" },
  "stage.LIVE": { en: "Live", de: "Live" },
  "stage.VERIFICATION": { en: "Verification", de: "Verifizierung" },
  "stage.PAYOUT": { en: "Payout", de: "Auszahlung" },

  // ----- what happens next
  "next.title": { en: "Next step", de: "Nächster Schritt" },
  "next.contract.sign": { en: "Read the contract and confirm it.", de: "Lies den Vertrag und bestätige ihn." },
  "next.contract.waiting": { en: "Waiting for {name} to confirm the contract.", de: "Warten auf die Bestätigung des Vertrags durch {name}." },
  "next.contract.stuck": { en: "Both sides confirmed, but the tax treatment could not be fixed yet. Check the business details and continue.", de: "Beide Seiten haben bestätigt, aber die Steuerbehandlung konnte noch nicht festgelegt werden. Prüfe die Geschäftsdaten und mach weiter." },
  "next.escrow.pay": { en: "Pay {amount} into escrow to start the work.", de: "Zahle {amount} ins Treuhandkonto ein, damit die Arbeit beginnt." },
  "next.escrow.waiting": { en: "Waiting for {name} to fund the escrow.", de: "Warten darauf, dass {name} das Treuhandkonto füllt." },
  "next.production.draft": { en: "Submit your draft by {date}.", de: "Reiche deinen Entwurf bis {date} ein." },
  "next.production.post": { en: "Publish the post by {date} and report the link.", de: "Veröffentliche den Post bis {date} und melde den Link." },
  "next.production.brand": { en: "The money is in escrow. {name} is working on the content.", de: "Das Geld liegt im Treuhandkonto. {name} arbeitet am Content." },
  "next.draft.review": { en: "Review the draft by {date}, otherwise it counts as approved.", de: "Prüfe den Entwurf bis {date}, sonst gilt er als freigegeben." },
  "next.draft.waiting": { en: "{name} is reviewing your draft (until {date}).", de: "{name} prüft deinen Entwurf (bis {date})." },
  "next.changes.creator": { en: "Revise your draft by {date}.", de: "Überarbeite deinen Entwurf bis {date}." },
  "next.changes.brand": { en: "Waiting for the revised draft from {name}.", de: "Warten auf den überarbeiteten Entwurf von {name}." },
  "next.approved.creator": { en: "Schedule the post, or publish it and report the link, by {date}.", de: "Plane den Post oder veröffentliche ihn und melde den Link bis {date}." },
  "next.approved.brand": { en: "Draft approved. {name} publishes by {date}.", de: "Entwurf freigegeben. {name} veröffentlicht bis {date}." },
  "next.scheduled.creator": { en: "Publish on {date} and report the link.", de: "Veröffentliche am {date} und melde den Link." },
  "next.scheduled.brand": { en: "The post is planned for {date}.", de: "Der Post ist für den {date} geplant." },
  "next.submitted.creator": { en: "We are checking your post.", de: "Wir prüfen deinen Post." },
  "next.submitted.brand": { en: "We are checking the post.", de: "Wir prüfen den Post." },
  "next.submittedProof.brand": { en: "Look at the proof and confirm the post.", de: "Sieh dir den Nachweis an und bestätige den Post." },
  "next.verifying": { en: "The post is verified. It has to stay live until {date}; then the payout is released.", de: "Der Post ist verifiziert. Er muss bis {date} online bleiben, dann wird die Auszahlung freigegeben." },
  "next.repost.creator": { en: "Your post is gone. Publish it again by {date}.", de: "Dein Post ist weg. Veröffentliche ihn bis {date} erneut." },
  "next.repost.brand": { en: "The post was removed. {name} has until {date} to publish it again.", de: "Der Post wurde entfernt. {name} hat bis {date} Zeit, ihn erneut zu veröffentlichen." },
  "next.payout": { en: "The payout is being released.", de: "Die Auszahlung wird freigegeben." },
  "next.payoutBlocked": { en: "The payout is ready, but payouts are not set up yet. Finish the setup to receive it.", de: "Die Auszahlung ist bereit, aber die Auszahlung ist noch nicht eingerichtet. Schließe die Einrichtung ab, um sie zu erhalten." },
  "next.completed": { en: "Done. The payout was released.", de: "Fertig. Die Auszahlung wurde freigegeben." },
  "next.disputed": { en: "Frozen. Our team is looking into it and will decide.", de: "Eingefroren. Unser Team prüft den Fall und entscheidet." },
  "next.cancelled": { en: "This deal was cancelled.", de: "Dieser Deal wurde abgebrochen." },
  "next.setupPayouts": { en: "Set up payouts", de: "Auszahlung einrichten" },

  // ----- deal page
  "deal.back": { en: "All deals", de: "Alle Deals" },
  "deal.with": { en: "with {name}", de: "mit {name}" },
  "deal.chat": { en: "Open chat", de: "Chat öffnen" },
  "deal.cancel": { en: "Cancel deal", de: "Deal abbrechen" },
  "deal.cancelled": { en: "The deal was cancelled.", de: "Der Deal wurde abgebrochen." },
  "deal.cancelConfirm": { en: "Cancel this deal? Nothing has been paid yet.", de: "Diesen Deal abbrechen? Es wurde noch nichts gezahlt." },
  "deal.cancelConfirmRefund": { en: "Cancel this deal? The brand gets the escrow back in full.", de: "Diesen Deal abbrechen? Die Marke bekommt das Treuhandgeld vollständig zurück." },
  "deal.timeline": { en: "History", de: "Verlauf" },
  "deal.noEvents": { en: "Nothing yet.", de: "Noch nichts." },

  // ----- contract
  "contract.title": { en: "Contract", de: "Vertrag" },
  "contract.intro": { en: "These are the terms of the briefing as they were when the offer was accepted. They can't change any more.", de: "Das sind die Bedingungen des Briefings zum Zeitpunkt der Annahme. Sie können sich nicht mehr ändern." },
  "contract.price": { en: "Price (net)", de: "Preis (netto)" },
  "contract.vat": { en: "VAT {rate} %", de: "USt. {rate} %" },
  "contract.total": { en: "Brand pays", de: "Marke zahlt" },
  "contract.vatPending": { en: "VAT is fixed when both sides have confirmed, from both business profiles.", de: "Die USt. wird festgelegt, sobald beide bestätigt haben, anhand beider Geschäftsprofile." },
  "contract.payout": { en: "Creator receives", de: "Creator erhält" },
  "contract.fee": { en: "comtor fee", de: "comtor-Gebühr" },
  "contract.formats": { en: "Content", de: "Content" },
  "contract.market": { en: "Advertising market", de: "Werbemarkt" },
  "contract.labels": { en: "Advertising label", de: "Werbekennzeichnung" },
  "contract.partnershipLabel": { en: "Platform paid-partnership label required", de: "Partnerschafts-Label der Plattform erforderlich" },
  "contract.hashtags": { en: "Required hashtags", de: "Pflicht-Hashtags" },
  "contract.mentions": { en: "Required mentions", de: "Pflicht-Erwähnungen" },
  "contract.talkingPoints": { en: "Talking points", de: "Kernbotschaften" },
  "contract.doNots": { en: "Don'ts", de: "Bitte vermeiden" },
  "contract.workflow": { en: "Process", de: "Ablauf" },
  "contract.draftRequired": { en: "Draft first, {days} days review, {rounds} revision rounds", de: "Erst Entwurf, {days} Tage Prüfzeit, {rounds} Korrekturrunden" },
  "contract.noDraft": { en: "No draft needed, post directly", de: "Kein Entwurf nötig, direkt posten" },
  "contract.window": { en: "Posting window", de: "Posting-Fenster" },
  "contract.windowFlexible": { en: "within {days} days after payment", de: "innerhalb von {days} Tagen nach Zahlung" },
  "contract.minLive": { en: "Stays live", de: "Bleibt online" },
  "contract.hours": { en: "{count} hours", de: "{count} Stunden" },
  "contract.days": { en: "{count} days", de: "{count} Tage" },
  "contract.exclusivity": { en: "Exclusivity", de: "Exklusivität" },
  "contract.exclusivityNone": { en: "None", de: "Keine" },
  "contract.exclusivityScope": { en: "{scope}: {before} days before, {after} days after publication", de: "{scope}: {before} Tage vor, {after} Tage nach Veröffentlichung" },
  "contract.exclusivityOwnCategory": { en: "Competitors in {category}", de: "Wettbewerber in {category}" },
  "contract.usage": { en: "Usage rights", de: "Nutzungsrechte" },
  "contract.usageOrganic": { en: "Posting on the creator's channel only", de: "Nur Posting auf dem Kanal des Creators" },
  "contract.usageCross": { en: "Repost on the brand's channels for {days} days", de: "Repost auf den Kanälen der Marke für {days} Tage" },
  "contract.usagePaid": { en: "Paid ads for {days} days ({channels}), {territory}, fee {fee}", de: "Bezahlte Ads für {days} Tage ({channels}), {territory}, Vergütung {fee}" },
  "contract.termsId": { en: "Terms ID", de: "Vertrags-ID" },
  "contract.signedBy": { en: "Confirmed by {name}", de: "Bestätigt von {name}" },
  "contract.notSigned": { en: "Not confirmed yet by {name}", de: "Noch nicht bestätigt von {name}" },
  "contract.continue": { en: "Continue", de: "Weiter" },
  "contract.continueHint": { en: "Both sides confirmed. Something in the business details or VAT IDs still has to be fixed before the payment can start.", de: "Beide Seiten haben bestätigt. In den Geschäftsdaten oder USt-IDs muss noch etwas geklärt werden, bevor die Zahlung starten kann." },
  "contract.sign": { en: "Confirm contract", de: "Vertrag bestätigen" },
  "contract.signed": { en: "Contract confirmed.", de: "Vertrag bestätigt." },
  "contract.signHint": { en: "By confirming you accept these terms, including the advertising labelling duty.", de: "Mit der Bestätigung akzeptierst du diese Bedingungen, einschließlich der Pflicht zur Werbekennzeichnung." },
  "contract.exclusivityWarning": { en: "Check your calendar", de: "Prüfe deinen Kalender" },

  // ----- escrow
  "escrow.title": { en: "Escrow", de: "Treuhandkonto" },
  "escrow.pay": { en: "Pay {amount} into escrow", de: "{amount} ins Treuhandkonto einzahlen" },
  "escrow.explain": { en: "The money is held until the post has been verified live and stayed up for the whole hold period. Then it is released to the creator.", de: "Das Geld wird gehalten, bis der Post als online verifiziert ist und die gesamte Haltefrist online blieb. Danach wird es an den Creator freigegeben." },
  "escrow.held": { en: "In escrow: {amount}", de: "Im Treuhandkonto: {amount}" },
  "escrow.refunded": { en: "Refunded: {amount}", de: "Erstattet: {amount}" },
  "escrow.released": { en: "Paid out", de: "Ausgezahlt" },
  "escrow.waiting": { en: "Not funded yet", de: "Noch nicht eingezahlt" },

  // ----- drafts
  "drafts.title": { en: "Drafts", de: "Entwürfe" },
  "drafts.none": { en: "No draft yet.", de: "Noch kein Entwurf." },
  "drafts.version": { en: "Draft {version}", de: "Entwurf {version}" },
  "drafts.status.SUBMITTED": { en: "Waiting for review", de: "Wartet auf Prüfung" },
  "drafts.status.APPROVED": { en: "Approved", de: "Freigegeben" },
  "drafts.status.CHANGES_REQUESTED": { en: "Changes requested", de: "Änderungen gewünscht" },
  "drafts.status.REJECTED": { en: "Rejected", de: "Abgelehnt" },
  "drafts.autoApproved": { en: "approved automatically after the review time", de: "automatisch nach Ablauf der Prüfzeit freigegeben" },
  "drafts.kind": { en: "What is it?", de: "Was ist es?" },
  "drafts.kind.SCRIPT": { en: "Script / storyboard", de: "Skript / Storyboard" },
  "drafts.kind.VIDEO_PREVIEW": { en: "Video preview", de: "Video-Vorschau" },
  "drafts.kind.IMAGE": { en: "Image", de: "Bild" },
  "drafts.kind.OTHER": { en: "Other", de: "Sonstiges" },
  "drafts.link": { en: "Link to the draft", de: "Link zum Entwurf" },
  "drafts.linkHint": { en: "Google Drive, Frame.io, an unlisted YouTube video …", de: "Google Drive, Frame.io, ein nicht gelistetes YouTube-Video …" },
  "drafts.notes": { en: "Notes (or paste the script here)", de: "Notizen (oder Skript hier einfügen)" },
  "drafts.caption": { en: "Planned caption", de: "Geplante Caption" },
  "drafts.captionHint": { en: "It is checked against the advertising rules now, so you don't find out after posting.", de: "Sie wird jetzt gegen die Werberegeln geprüft, damit du es nicht erst nach dem Posten erfährst." },
  "drafts.disclosureInContent": { en: "The content itself (spoken or on screen) marks the advertising.", de: "Der Inhalt selbst (gesprochen oder eingeblendet) kennzeichnet die Werbung." },
  "drafts.submit": { en: "Submit draft", de: "Entwurf einreichen" },
  "drafts.resubmit": { en: "Submit revised draft", de: "Überarbeiteten Entwurf einreichen" },
  "drafts.submitted": { en: "Draft submitted.", de: "Entwurf eingereicht." },
  "drafts.feedback": { en: "Feedback for the creator", de: "Feedback für den Creator" },
  "drafts.roundsLeft": { en: "{count} revision rounds left.", de: "Noch {count} Korrekturrunden." },
  "drafts.noRoundsLeft": { en: "No revision rounds left: approve, or reject to have the deal reviewed.", de: "Keine Korrekturrunden mehr: Gib frei oder lehne ab, damit der Deal geprüft wird." },
  "drafts.approve": { en: "Approve draft", de: "Entwurf freigeben" },
  "drafts.requestChanges": { en: "Request changes", de: "Änderungen anfordern" },
  "drafts.reject": { en: "Reject (opens a review)", de: "Ablehnen (löst Prüfung aus)" },
  "drafts.reviewed": { en: "Done.", de: "Erledigt." },
  "drafts.reviewBy": { en: "Review by {date}", de: "Prüfung bis {date}" },

  // ----- posts
  "posts.title": { en: "Posts", de: "Posts" },
  "posts.none": { en: "No post reported yet.", de: "Noch kein Post gemeldet." },
  "posts.status.PENDING": { en: "Being checked", de: "Wird geprüft" },
  "posts.status.VERIFIED": { en: "Verified live", de: "Online verifiziert" },
  "posts.status.REMOVED": { en: "Removed", de: "Entfernt" },
  "posts.status.UNREACHABLE": { en: "Can't be reached", de: "Nicht erreichbar" },
  "posts.status.REJECTED": { en: "Replaced", de: "Ersetzt" },
  "posts.source.MANUAL": { en: "reported by the creator", de: "vom Creator gemeldet" },
  "posts.source.OEMBED": { en: "checked on the platform", de: "auf der Plattform geprüft" },
  "posts.source.API": { en: "checked through the platform API", de: "über die Plattform-API geprüft" },
  "posts.source.WEBHOOK": { en: "confirmed by the platform", de: "von der Plattform bestätigt" },
  "posts.source.PROOF": { en: "proof screenshot", de: "Nachweis per Screenshot" },
  "posts.publishedAt": { en: "Published at", de: "Veröffentlicht am" },
  "posts.lastChecked": { en: "Last check {date}", de: "Letzte Prüfung {date}" },
  "posts.views": { en: "{count} views", de: "{count} Aufrufe" },
  "posts.likes": { en: "{count} likes", de: "{count} Likes" },
  "posts.label": { en: "Label: {label}", de: "Kennzeichnung: {label}" },
  "posts.labelMissing": { en: "No label found in the caption", de: "Keine Kennzeichnung in der Caption gefunden" },
  "posts.partnershipOn": { en: "Platform label on", de: "Plattform-Label an" },
  "posts.proof": { en: "Proof", de: "Nachweis" },
  "posts.confirm": { en: "Confirm post", de: "Post bestätigen" },
  "posts.confirmed": { en: "Post confirmed.", de: "Post bestätigt." },
  "posts.confirmBy": { en: "Counts as confirmed automatically on {date}.", de: "Gilt am {date} automatisch als bestätigt." },
  "posts.recheck": { en: "Check now", de: "Jetzt prüfen" },
  "posts.rechecked": { en: "Checked.", de: "Geprüft." },
  "posts.scheduleTitle": { en: "Schedule the post", de: "Post planen" },
  "posts.scheduleAt": { en: "Planned for", de: "Geplant für" },
  "posts.schedule": { en: "Schedule", de: "Planen" },
  "posts.reschedule": { en: "Change date", de: "Datum ändern" },
  "posts.scheduled": { en: "Post scheduled.", de: "Post geplant." },
  "posts.scheduledFor": { en: "Planned for {date}", de: "Geplant für {date}" },
  "posts.reportTitle": { en: "Report the live post", de: "Live-Post melden" },
  "posts.format": { en: "Format", de: "Format" },
  "posts.link": { en: "Link to the post", de: "Link zum Post" },
  "posts.linkOptional": { en: "Link to the post (optional)", de: "Link zum Post (optional)" },
  "posts.linkHint": { en: "The full address of the post, not a share or short link.", de: "Die vollständige Adresse des Posts, kein Share- oder Kurzlink." },
  "posts.caption": { en: "Caption as published", de: "Caption wie veröffentlicht" },
  "posts.captionHint": { en: "The label ({labels}) has to stand within the first {chars} characters.", de: "Die Kennzeichnung ({labels}) muss in den ersten {chars} Zeichen stehen." },
  "posts.disclosureInContent": { en: "The video itself marks the advertising (spoken or on screen).", de: "Das Video selbst kennzeichnet die Werbung (gesprochen oder eingeblendet)." },
  "posts.disclosureStory": { en: "The story shows a label such as “Werbung” on screen.", de: "Die Story zeigt eine Kennzeichnung wie „Werbung“ im Bild." },
  "posts.partnershipLabel": { en: "The platform label is switched on: {label}.", de: "Das Plattform-Label ist eingeschaltet: {label}." },
  "posts.publishedAtField": { en: "Went live at", de: "Online gegangen am" },
  "posts.proofRequired": { en: "Screenshot (required)", de: "Screenshot (erforderlich)" },
  "posts.proofOptional": { en: "Screenshot (optional)", de: "Screenshot (optional)" },
  "posts.proofHint": { en: "Shows the post with its label. Stored privately; only you, the other side and comtor staff can see it.", de: "Zeigt den Post mit Kennzeichnung. Privat gespeichert; nur du, die Gegenseite und das comtor-Team sehen ihn." },
  "posts.proofUnreadable": { en: "That image couldn't be read. Try a JPEG or PNG.", de: "Das Bild konnte nicht gelesen werden. Versuche ein JPEG oder PNG." },
  "posts.submit": { en: "Report post", de: "Post melden" },
  "posts.submitted": { en: "Post reported. We are checking it.", de: "Post gemeldet. Wir prüfen ihn." },
  "posts.holdUntil": { en: "Has to stay live until {date}", de: "Muss online bleiben bis {date}" },

  // ----- usage rights
  "usage.title": { en: "Usage rights", de: "Nutzungsrechte" },
  "usage.state.NOT_APPLICABLE": { en: "Not part of this deal", de: "Nicht Teil dieses Deals" },
  "usage.state.NOT_STARTED": { en: "Starts when the post is verified live", de: "Beginnen, sobald der Post als online verifiziert ist" },
  "usage.state.ACTIVE": { en: "Active until {date}", de: "Aktiv bis {date}" },
  "usage.state.EXPIRING": { en: "Ends soon: {date}", de: "Enden bald: {date}" },
  "usage.state.EXPIRED": { en: "Ended on {date}. The post must no longer be used as an ad.", de: "Am {date} abgelaufen. Der Post darf nicht mehr als Anzeige genutzt werden." },
  "usage.deliverTitle": { en: "Hand over the ad rights", de: "Ads-Rechte übergeben" },
  "usage.deliverHint": { en: "The payout waits for this.", de: "Die Auszahlung wartet darauf." },
  "usage.sparkCode": { en: "TikTok Spark Ads code", de: "TikTok-Spark-Ads-Code" },
  "usage.sparkCodeHint": { en: "From TikTok: video settings → Ad settings → Authorise.", de: "In TikTok: Videoeinstellungen → Anzeigeneinstellungen → Autorisieren." },
  "usage.sparkExpires": { en: "Code valid until", de: "Code gültig bis" },
  "usage.permission": { en: "I granted the partner-ad permission for the brand's account (Meta / YouTube / whitelisting).", de: "Ich habe der Marke die Partner-Ad-Berechtigung erteilt (Meta / YouTube / Whitelisting)." },
  "usage.deliver": { en: "Hand over", de: "Übergeben" },
  "usage.delivered": { en: "Handed over.", de: "Übergeben." },
  "usage.deliveredAt": { en: "Handed over on {date}", de: "Übergeben am {date}" },
  "usage.notDelivered": { en: "Not handed over yet", de: "Noch nicht übergeben" },
  "usage.code": { en: "Spark Ads code: {code}", de: "Spark-Ads-Code: {code}" },
  "usage.confirm": { en: "Confirm received", de: "Erhalt bestätigen" },
  "usage.confirmed": { en: "Confirmed.", de: "Bestätigt." },

  // ----- disputes
  "dispute.title": { en: "Report a problem", de: "Problem melden" },
  "dispute.open": { en: "Something is wrong? Report a problem", de: "Stimmt etwas nicht? Problem melden" },
  "dispute.explain": { en: "The deal and the payment are frozen until our team has looked at it and decided. Please only use this if you can't sort it out with the other side.", de: "Der Deal und die Zahlung werden eingefroren, bis unser Team den Fall geprüft und entschieden hat. Nutze das nur, wenn ihr es nicht mit der Gegenseite klären könnt." },
  "dispute.reason": { en: "What is the problem?", de: "Worin besteht das Problem?" },
  "dispute.reason.MISSED_DEADLINE": { en: "A deadline was missed", de: "Eine Frist wurde verpasst" },
  "dispute.reason.DRAFT_REJECTED": { en: "The draft was rejected", de: "Der Entwurf wurde abgelehnt" },
  "dispute.reason.POST_REMOVED": { en: "The post was removed", de: "Der Post wurde entfernt" },
  "dispute.reason.DISCLOSURE_MISSING": { en: "The advertising label is missing", de: "Die Werbekennzeichnung fehlt" },
  "dispute.reason.CONTENT_MISMATCH": { en: "The content doesn't match the briefing", de: "Der Inhalt entspricht nicht dem Briefing" },
  "dispute.reason.USAGE_RIGHTS_MISSING": { en: "The ad usage rights weren't handed over", de: "Die Ads-Nutzungsrechte wurden nicht übergeben" },
  "dispute.reason.OTHER": { en: "Something else", de: "Etwas anderes" },
  "dispute.details": { en: "What happened?", de: "Was ist passiert?" },
  "dispute.detailsHint": { en: "A few sentences. Both sides see this.", de: "Ein paar Sätze. Beide Seiten sehen das." },
  "dispute.submit": { en: "Freeze and report", de: "Einfrieren und melden" },
  "dispute.opened": { en: "Reported. The payment is frozen.", de: "Gemeldet. Die Zahlung ist eingefroren." },
  "dispute.openedBy": { en: "Opened by {who} on {date}", de: "Eröffnet von {who} am {date}" },
  "dispute.bySystem": { en: "comtor (automatic)", de: "comtor (automatisch)" },
  "dispute.status.OPEN": { en: "Under review", de: "In Prüfung" },
  "dispute.status.RESOLVED_RELEASE": { en: "Decided: paid out to the creator", de: "Entschieden: an den Creator ausgezahlt" },
  "dispute.status.RESOLVED_REFUND": { en: "Decided: refunded to the brand", de: "Entschieden: an die Marke erstattet" },
  "dispute.status.RESOLVED_RESUME": { en: "Decided: the deal continues", de: "Entschieden: Der Deal läuft weiter" },
  "dispute.resolution": { en: "Reason: {text}", de: "Begründung: {text}" },

  // ----- invoices
  "invoices.title": { en: "Invoices", de: "Rechnungen" },
  "invoices.none": { en: "Invoices are issued when the payout is released.", de: "Rechnungen werden mit der Freigabe der Auszahlung erstellt." },
  "invoices.kind.BRAND_INVOICE": { en: "Invoice", de: "Rechnung" },
  "invoices.kind.CREATOR_CREDIT_NOTE": { en: "Credit note", de: "Gutschrift" },
  "invoices.open": { en: "Open", de: "Öffnen" },
  "invoices.issuedOn": { en: "{date}", de: "{date}" },
  "invoices.listTitle": { en: "Invoices & credit notes", de: "Rechnungen & Gutschriften" },
  "invoices.listDescription": { en: "Issued for finished deals. Keep them for your accounts.", de: "Für abgeschlossene Deals ausgestellt. Bewahre sie für deine Buchhaltung auf." },
  "invoices.number": { en: "No.", de: "Nr." },
  "invoices.date": { en: "Date", de: "Datum" },
  "invoices.servicePeriod": { en: "Service period", de: "Leistungszeitraum" },
  "invoices.from": { en: "From", de: "Von" },
  "invoices.to": { en: "To", de: "An" },
  "invoices.description": { en: "Description", de: "Beschreibung" },
  "invoices.qty": { en: "Qty", de: "Menge" },
  "invoices.net": { en: "Net", de: "Netto" },
  "invoices.vat": { en: "VAT {rate} %", de: "USt. {rate} %" },
  "invoices.vatNone": { en: "VAT", de: "USt." },
  "invoices.gross": { en: "Total", de: "Gesamt" },
  "invoices.grossCredit": { en: "Payout amount", de: "Auszahlungsbetrag" },
  "invoices.vatId": { en: "VAT ID {id}", de: "USt-IdNr. {id}" },
  "invoices.taxNumber": { en: "Tax no. {id}", de: "Steuernr. {id}" },
  "invoices.deal": { en: "Deal", de: "Deal" },
  "invoices.cancelled": { en: "Cancelled", de: "Storniert" },
  "invoices.empty": { en: "No invoices yet.", de: "Noch keine Rechnungen." },

  // ----- timeline events
  "event.deal.created": { en: "Deal created from the accepted offer", de: "Deal aus dem angenommenen Angebot erstellt" },
  "event.contract.signed": { en: "Contract confirmed", de: "Vertrag bestätigt" },
  "event.contract.completed": { en: "Both sides confirmed; tax treatment fixed", de: "Beide Seiten bestätigt; Steuerbehandlung festgelegt" },
  "event.status.IN_PRODUCTION": { en: "Escrow funded, work started", de: "Treuhandkonto gefüllt, Arbeit gestartet" },
  "event.draft.submitted": { en: "Draft submitted", de: "Entwurf eingereicht" },
  "event.draft.approved": { en: "Draft approved", de: "Entwurf freigegeben" },
  "event.draft.auto_approved": { en: "Draft approved automatically (review time ran out)", de: "Entwurf automatisch freigegeben (Prüfzeit abgelaufen)" },
  "event.draft.changes_requested": { en: "Changes requested", de: "Änderungen angefordert" },
  "event.post.scheduled": { en: "Post scheduled", de: "Post geplant" },
  "event.post.submitted": { en: "Post reported", de: "Post gemeldet" },
  "event.status.VERIFYING": { en: "Post verified live, hold period started", de: "Post online verifiziert, Haltefrist gestartet" },
  "event.status.REPOST_REQUIRED": { en: "Post no longer reachable", de: "Post nicht mehr erreichbar" },
  "event.status.PAYOUT_PENDING": { en: "Hold period over, payout due", de: "Haltefrist vorbei, Auszahlung fällig" },
  "event.status.COMPLETED": { en: "Payout released", de: "Auszahlung freigegeben" },
  "event.disclosure.check_failed": { en: "Caption on the platform may lack the advertising label", de: "Caption auf der Plattform enthält evtl. keine Werbekennzeichnung" },
  "event.usage.delivered": { en: "Ad usage rights handed over", de: "Ads-Nutzungsrechte übergeben" },
  "event.usage.confirmed": { en: "Ad usage rights confirmed", de: "Ads-Nutzungsrechte bestätigt" },
  "event.dispute.opened": { en: "Dispute opened, deal frozen", de: "Streitfall eröffnet, Deal eingefroren" },
  "event.dispute.released": { en: "Dispute decided: payout to the creator", de: "Streitfall entschieden: Auszahlung an den Creator" },
  "event.dispute.refunded": { en: "Dispute decided: refund to the brand", de: "Streitfall entschieden: Erstattung an die Marke" },
  "event.dispute.resumed": { en: "Dispute decided: the deal continues", de: "Streitfall entschieden: Der Deal läuft weiter" },
  "event.cancelled": { en: "Deal cancelled", de: "Deal abgebrochen" },
  "event.by.STARTUP": { en: "brand", de: "Marke" },
  "event.by.CREATOR": { en: "creator", de: "Creator" },
  "event.by.ADMIN": { en: "comtor team", de: "comtor-Team" },
  "event.by.SYSTEM": { en: "automatic", de: "automatisch" },

  // ----- tax
  "tax.DOMESTIC_VAT": { en: "German VAT", de: "Deutsche Umsatzsteuer" },
  "tax.REVERSE_CHARGE_EU": { en: "Reverse charge (EU)", de: "Reverse Charge (EU)" },
  "tax.REVERSE_CHARGE_13B": { en: "Reverse charge § 13b UStG", de: "Reverse Charge § 13b UStG" },
  "tax.OUT_OF_SCOPE": { en: "Not taxable in Germany", de: "Nicht im Inland steuerbar" },
  "tax.SMALL_BUSINESS_EXEMPT": { en: "Small business, no VAT", de: "Kleinunternehmer, keine USt." },
  "tax.treatment": { en: "Tax treatment", de: "Steuerbehandlung" },
} as const satisfies Record<string, Text>;

const WORDS = { ...CORE_WORDS, ...BUSINESS_WORDS, ...BRIEFING_WORDS };

export type UiKey = keyof typeof WORDS;

export type UiText = (key: UiKey, vars?: Record<string, string | number>) => string;

export function uiText(locale: DealLocale): UiText {
  return (key, vars) => fill(WORDS[key][locale], vars);
}

export const UI_WORDS: Record<UiKey, Text> = WORDS;
