// Writes public/third-party-notices.txt: the licence texts of the open-source packages the deployed app
// ships (production dependencies of package-lock.json), as MIT, BSD, Apache and similar licences ask. Run it
// after dependencies change:  npm run licenses:generate   (needs node_modules installed)
import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const lock = JSON.parse(fs.readFileSync(path.join(ROOT, "package-lock.json"), "utf8"));
const LICENSE_FILE = /^(licen[sc]e|copying|notice|unlicense)([.-].*)?$/i;
const MAX_TEXT = 40_000;

const packages = [];
for (const [key, meta] of Object.entries(lock.packages)) {
  if (!key.includes("node_modules/") || meta.dev || meta.devOptional) continue;
  const name = key.split("node_modules/").pop();
  const dir = path.join(ROOT, key);
  let license = typeof meta.license === "object" ? JSON.stringify(meta.license) : meta.license;
  if (!license && fs.existsSync(path.join(dir, "package.json"))) {
    // Old packages say it in their own package.json (an array of {type}) or only in a LICENSE file.
    const own = JSON.parse(fs.readFileSync(path.join(dir, "package.json"), "utf8"));
    license = typeof own.license === "string" ? own.license : own.licenses?.map((l) => l.type).join(" OR ");
  }
  license ||= "see licence text";
  const texts = [];
  if (fs.existsSync(dir)) {
    for (const file of fs.readdirSync(dir).filter((f) => LICENSE_FILE.test(f)).sort()) {
      const full = path.join(dir, file);
      if (!fs.statSync(full).isFile()) continue;
      texts.push(fs.readFileSync(full, "utf8").replace(/\r\n/g, "\n").trim().slice(0, MAX_TEXT));
    }
  }
  packages.push({ name, version: meta.version, license, text: texts.join("\n\n") });
}
packages.sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version));

// Packages with the same licence text share one copy of it.
const groups = new Map();
for (const pkg of packages) {
  const text = pkg.text || `(The package declares the licence ${pkg.license} but ships no licence text.)`;
  if (!groups.has(text)) groups.set(text, []);
  groups.get(text).push(pkg);
}

const lines = [
  "Third-party software in comtor",
  "",
  `Licence notices for the ${packages.length} open-source packages the deployed app is built with.`,
  "Generated by scripts/generate-notices.mjs from package-lock.json. Do not edit by hand.",
  "",
];
for (const [text, group] of groups) {
  lines.push("=".repeat(78));
  for (const pkg of group) lines.push(`${pkg.name}@${pkg.version} (${pkg.license})`);
  lines.push("-".repeat(78), text, "");
}
fs.writeFileSync(path.join(ROOT, "public/third-party-notices.txt"), lines.join("\n"));

const byLicense = {};
for (const pkg of packages) byLicense[pkg.license] = (byLicense[pkg.license] || 0) + 1;
console.log(`${packages.length} packages, ${groups.size} distinct texts`);
console.log(Object.entries(byLicense).sort((a, b) => b[1] - a[1]).map(([k, v]) => `${k}: ${v}`).join(" | "));
